### ISSUE TITLE
[9.0] Documentation does not match the installed applications

### ISSUE THREAD

**Issue by kenneth-vkd** [clouder-community/clouder#138]
Hi
We just came across this tool and it is just what we were looking for. So I created two virtual machines using vagrant and virtualbox to test the application.
However we have come across a big issue with the getting started guide.
http://clouder.readthedocs.io/en/0.9.0/connect-server.html
The guidance and screenshots seems to be for Odoo version 8 and not for version 9, although the applications install fine on Odoo 9 installed in Debian 8.
I tested with the latest version of Odoo 9 Community Edition and also Odoo 9 Enterprise Edition, but when I come to step where I have to create the server, I get issues.
I create a new server record and copy the public SSH key to the container-host in `/root/.ssh/authorized_keys`
Then I save the record and it starts processing.
After some time it displays an error:
```
We were not able to assign an hostport to the localport 4506.
If you don't want to assign one manually, make sure you fill the port range in the server configuration, and that all ports in that range are not already used.
```
Looking at the log files it seems to connect fine, but something is wrong regarding a container that is expected to be there, but nowhere in the getting started guide we are asked to create it.
This is the logfile:
```
2016-10-14 09:11:28 : command : /opt/odoo/addons/clouder/res/sed.sh container-host.clouder-local /var/lib/odoo/.ssh/config
2016-10-14 09:11:28 : connect: ssh root@192.168.33.65 -p 22
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker stop docker-salt-master
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : stderr : Error: failed to stop containers: [docker-salt-master]
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker exec docker-salt-master bash -c  "sed -i \"/containers\/docker-salt-master/d\" /srv/pillar/top.sls "
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker exec docker-salt-master bash -c  "rm -rf /srv/salt/containers/build_docker-salt-master "
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker exec docker-salt-master bash -c  "rm -rf /srv/pillar/containers/docker-salt-master.sls "
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker rm -v docker-salt-master
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : stderr : Error: failed to remove containers: [docker-salt-master]
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker stop docker-salt-master-data
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master-data
2016-10-14 09:11:29 : stderr : Error: failed to stop containers: [docker-salt-master-data]
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker exec docker-salt-master bash -c  "sed -i \"/containers\/docker-salt-master-data/d\" /srv/pillar/top.sls "
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker exec docker-salt-master bash -c  "rm -rf /srv/salt/containers/build_docker-salt-master-data "
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker exec docker-salt-master bash -c  "rm -rf /srv/pillar/containers/docker-salt-master-data.sls "
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:11:29 : host : container-host.clouder-local
2016-10-14 09:11:29 : command : docker rm -v docker-salt-master-data
2016-10-14 09:11:29 : stderr : Error response from daemon: no such id: docker-salt-master-data
2016-10-14 09:11:30 : stderr : Error: failed to remove containers: [docker-salt-master-data]
2016-10-14 09:11:30 : host : container-host.clouder-local
2016-10-14 09:11:30 : command : rm -rf /tmp/docker-salt-master-data-20161014.091130
2016-10-14 09:11:30 : host : container-host.clouder-local
2016-10-14 09:11:30 : command : mkdir -p /tmp/docker-salt-master-data-20161014.091130
2016-10-14 09:11:30 : Send directory /opt/odoo/addons/clouder/sources to /tmp/docker-salt-master-data-20161014.091130/sources
2016-10-14 09:11:30 : host : container-host.clouder-local
2016-10-14 09:11:30 : command : mkdir -p /tmp/docker-salt-master-data-20161014.091130/sources
2016-10-14 09:11:30 : dirpath /opt/odoo/addons/clouder/sources
2016-10-14 09:11:30 : dirnames [u'salt-master', u'_modules']
2016-10-14 09:11:30 : filenames [u'check_mem.pl', u'salt-api.conf', u'__init__.py', u'reactor.conf', u'check_backup']
2016-10-14 09:11:30 : host : container-host.clouder-local
2016-10-14 09:11:30 : command : mkdir -p /tmp/docker-salt-master-data-20161014.091130/sources/./salt-master
2016-10-14 09:11:30 : host : container-host.clouder-local
2016-10-14 09:11:30 : command : mkdir -p /tmp/docker-salt-master-data-20161014.091130/sources/./_modules
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/check_mem.pl to /tmp/docker-salt-master-data-20161014.091130/sources/./check_mem.pl
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/salt-api.conf to /tmp/docker-salt-master-data-20161014.091130/sources/./salt-api.conf
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/__init__.py to /tmp/docker-salt-master-data-20161014.091130/sources/./__init__.py
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/reactor.conf to /tmp/docker-salt-master-data-20161014.091130/sources/./reactor.conf
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/check_backup to /tmp/docker-salt-master-data-20161014.091130/sources/./check_backup
2016-10-14 09:11:30 : dirpath /opt/odoo/addons/clouder/sources/salt-master
2016-10-14 09:11:30 : dirnames [u'_modules']
2016-10-14 09:11:30 : filenames [u'container_purge.sls', u'base_update.sls', u'container_stop.sls', u'container_start.sls', u'container_deploy_api.sls', u'container_deploy.sls']
2016-10-14 09:11:30 : host : container-host.clouder-local
2016-10-14 09:11:30 : command : mkdir -p /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/_modules
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/salt-master/container_purge.sls to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/container_purge.sls
2016-10-14 09:11:30 : send : /opt/odoo/addons/clouder/sources/salt-master/base_update.sls to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/base_update.sls
2016-10-14 09:11:31 : send : /opt/odoo/addons/clouder/sources/salt-master/container_stop.sls to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/container_stop.sls
2016-10-14 09:11:31 : send : /opt/odoo/addons/clouder/sources/salt-master/container_start.sls to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/container_start.sls
2016-10-14 09:11:31 : send : /opt/odoo/addons/clouder/sources/salt-master/container_deploy_api.sls to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/container_deploy_api.sls
2016-10-14 09:11:31 : send : /opt/odoo/addons/clouder/sources/salt-master/container_deploy.sls to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/container_deploy.sls
2016-10-14 09:11:31 : dirpath /opt/odoo/addons/clouder/sources/salt-master/_modules
2016-10-14 09:11:31 : dirnames []
2016-10-14 09:11:31 : filenames [u'clouder.py']
2016-10-14 09:11:31 : send : /opt/odoo/addons/clouder/sources/salt-master/_modules/clouder.py to /tmp/docker-salt-master-data-20161014.091130/sources/salt-master/_modules/clouder.py
2016-10-14 09:11:31 : dirpath /opt/odoo/addons/clouder/sources/_modules
2016-10-14 09:11:31 : dirnames []
2016-10-14 09:11:31 : filenames [u'clouder.py']
2016-10-14 09:11:31 : send : /opt/odoo/addons/clouder/sources/_modules/clouder.py to /tmp/docker-salt-master-data-20161014.091130/sources/_modules/clouder.py
2016-10-14 09:11:31 : host : container-host.clouder-local
2016-10-14 09:11:31 : command : echo "FROM clouder/clouder-salt-master-data
MAINTAINER kenneth@vkdata.dk

VOLUME /srv/salt /srv/pillar " >> /tmp/docker-salt-master-data-20161014.091130/Dockerfile
2016-10-14 09:11:31 : host : container-host.clouder-local
2016-10-14 09:11:31 : command : docker build --pull -t docker-salt-master-data-20161014.091130 /tmp/docker-salt-master-data-20161014.091130
2016-10-14 09:11:31 : stdout : Sending build context to Docker daemon 29.18 kB
Sending build context to Docker daemon 29.18 kB

2016-10-14 09:11:31 : stdout : Step 1 : FROM clouder/clouder-salt-master-data
2016-10-14 09:11:34 : stdout : latest: Pulling from clouder/clouder-salt-master-data
2016-10-14 09:11:34 : stdout : d5c7c4625536: Pulling fs layer
2016-10-14 09:11:34 : stdout : 63e0c13f7819: Pulling fs layer
2016-10-14 09:11:34 : stdout : 0bc1db706353: Pulling fs layer
2016-10-14 09:11:34 : stdout : 906ea9b77b3f: Pulling fs layer
2016-10-14 09:11:34 : stdout : 6bea758792bc: Pulling fs layer
2016-10-14 09:11:34 : stdout : 6cae33cdac1c: Pulling fs layer
2016-10-14 09:11:34 : stdout : 2b18704a61ae: Pulling fs layer
2016-10-14 09:11:34 : stdout : c67fbaffd0ff: Pulling fs layer
2016-10-14 09:11:34 : stdout : 099e59303b9e: Pulling fs layer
2016-10-14 09:11:34 : stdout : 27d68926f362: Pulling fs layer
2016-10-14 09:11:34 : stdout : b930e4ed078a: Pulling fs layer
2016-10-14 09:11:34 : stdout : d459745cfe33: Pulling fs layer
2016-10-14 09:11:34 : stdout : 0300d74fa35e: Pulling fs layer
2016-10-14 09:11:34 : stdout : 9dfbe84239d4: Pulling fs layer
2016-10-14 09:11:34 : stdout : a0f950ea2cbd: Pulling fs layer
2016-10-14 09:11:34 : stdout : b6fec035f243: Pulling fs layer
2016-10-14 09:11:34 : stdout : 8ee9b427502c: Pulling fs layer
2016-10-14 09:11:34 : stdout : a268c3e18785: Pulling fs layer
2016-10-14 09:11:34 : stdout : 88e8571d2ee0: Pulling fs layer
2016-10-14 09:11:34 : stdout : 8b3a1f752216: Pulling fs layer
2016-10-14 09:11:34 : stdout : 8aa917ed1723: Pulling fs layer
2016-10-14 09:11:34 : stdout : e46b954033e9: Pulling fs layer
2016-10-14 09:11:34 : stdout : 27890353805b: Pulling fs layer
2016-10-14 09:11:34 : stdout : 6fd49fdeef2b: Pulling fs layer
2016-10-14 09:11:34 : stdout : 6f56885abba8: Pulling fs layer
2016-10-14 09:11:34 : stdout : 38576cfda9cf: Pulling fs layer
2016-10-14 09:11:34 : stdout : 5e1e523d61e8: Pulling fs layer
2016-10-14 09:11:36 : stdout : b930e4ed078a: Verifying Checksum
2016-10-14 09:11:36 : stdout : b930e4ed078a: Download complete
2016-10-14 09:11:36 : stdout : 0bc1db706353: Verifying Checksum
2016-10-14 09:11:36 : stdout : 0bc1db706353: Download complete
2016-10-14 09:11:36 : stdout : b6fec035f243: Verifying Checksum
2016-10-14 09:11:36 : stdout : b6fec035f243: Download complete
2016-10-14 09:11:36 : stdout : 63e0c13f7819: Verifying Checksum
2016-10-14 09:11:36 : stdout : 63e0c13f7819: Download complete
2016-10-14 09:11:36 : stdout : 6bea758792bc: Verifying Checksum
2016-10-14 09:11:36 : stdout : 6bea758792bc: Download complete
2016-10-14 09:11:36 : stdout : 099e59303b9e: Verifying Checksum
2016-10-14 09:11:36 : stdout : 099e59303b9e: Download complete
2016-10-14 09:11:36 : stdout : 906ea9b77b3f: Verifying Checksum
2016-10-14 09:11:36 : stdout : 906ea9b77b3f: Download complete
2016-10-14 09:11:36 : stdout : 2b18704a61ae: Verifying Checksum
2016-10-14 09:11:36 : stdout : 2b18704a61ae: Download complete
2016-10-14 09:11:36 : stdout : 6cae33cdac1c: Verifying Checksum
2016-10-14 09:11:36 : stdout : 6cae33cdac1c: Download complete
2016-10-14 09:11:36 : stdout : 27d68926f362: Verifying Checksum
2016-10-14 09:11:36 : stdout : 27d68926f362: Download complete
2016-10-14 09:11:36 : stdout : 6fd49fdeef2b: Verifying Checksum
2016-10-14 09:11:36 : stdout : 6fd49fdeef2b: Download complete
2016-10-14 09:11:36 : stdout : 9dfbe84239d4: Verifying Checksum
2016-10-14 09:11:36 : stdout : 9dfbe84239d4: Download complete
2016-10-14 09:11:36 : stdout : 8aa917ed1723: Verifying Checksum
2016-10-14 09:11:36 : stdout : 8aa917ed1723: Download complete
2016-10-14 09:11:36 : stdout : 38576cfda9cf: Verifying Checksum
2016-10-14 09:11:36 : stdout : 38576cfda9cf: Download complete
2016-10-14 09:11:36 : stdout : a268c3e18785: Verifying Checksum
2016-10-14 09:11:36 : stdout : a268c3e18785: Download complete
2016-10-14 09:11:36 : stdout : 8ee9b427502c: Verifying Checksum
2016-10-14 09:11:36 : stdout : 8ee9b427502c: Download complete
2016-10-14 09:11:36 : stdout : e46b954033e9: Verifying Checksum
2016-10-14 09:11:36 : stdout : e46b954033e9: Download complete
2016-10-14 09:11:36 : stdout : a0f950ea2cbd: Verifying Checksum
2016-10-14 09:11:36 : stdout : a0f950ea2cbd: Download complete
2016-10-14 09:11:36 : stdout : 6f56885abba8: Verifying Checksum
2016-10-14 09:11:36 : stdout : 6f56885abba8: Download complete
2016-10-14 09:11:36 : stdout : 27890353805b: Verifying Checksum
2016-10-14 09:11:36 : stdout : 27890353805b: Download complete
2016-10-14 09:11:36 : stdout : 5e1e523d61e8: Verifying Checksum
2016-10-14 09:11:36 : stdout : 5e1e523d61e8: Download complete
2016-10-14 09:11:36 : stdout : 8b3a1f752216: Verifying Checksum
2016-10-14 09:11:36 : stdout : 8b3a1f752216: Download complete
2016-10-14 09:11:37 : stdout : 88e8571d2ee0: Verifying Checksum
2016-10-14 09:11:37 : stdout : 88e8571d2ee0: Download complete
2016-10-14 09:11:37 : stdout : c67fbaffd0ff: Verifying Checksum
2016-10-14 09:11:37 : stdout : c67fbaffd0ff: Download complete
2016-10-14 09:11:51 : stdout : d459745cfe33: Verifying Checksum
2016-10-14 09:11:51 : stdout : d459745cfe33: Download complete
2016-10-14 09:11:53 : stdout : d5c7c4625536: Verifying Checksum
2016-10-14 09:11:53 : stdout : d5c7c4625536: Download complete
2016-10-14 09:11:54 : stdout : 0300d74fa35e: Verifying Checksum
2016-10-14 09:11:54 : stdout : 0300d74fa35e: Download complete
2016-10-14 09:11:57 : stdout : d5c7c4625536: Pull complete
2016-10-14 09:11:57 : stdout : 63e0c13f7819: Pull complete
2016-10-14 09:11:57 : stdout : 0bc1db706353: Pull complete
2016-10-14 09:11:57 : stdout : 906ea9b77b3f: Pull complete
2016-10-14 09:11:57 : stdout : 6bea758792bc: Pull complete
2016-10-14 09:11:57 : stdout : 6cae33cdac1c: Pull complete
2016-10-14 09:11:57 : stdout : 2b18704a61ae: Pull complete
2016-10-14 09:11:57 : stdout : c67fbaffd0ff: Pull complete
2016-10-14 09:11:57 : stdout : 099e59303b9e: Pull complete
2016-10-14 09:11:57 : stdout : 27d68926f362: Pull complete
2016-10-14 09:11:57 : stdout : b930e4ed078a: Pull complete
2016-10-14 09:11:58 : stdout : d459745cfe33: Pull complete
2016-10-14 09:12:03 : stdout : 0300d74fa35e: Pull complete
2016-10-14 09:12:03 : stdout : 9dfbe84239d4: Pull complete
2016-10-14 09:12:03 : stdout : a0f950ea2cbd: Pull complete
2016-10-14 09:12:03 : stdout : b6fec035f243: Pull complete
2016-10-14 09:12:03 : stdout : 8ee9b427502c: Pull complete
2016-10-14 09:12:03 : stdout : a268c3e18785: Pull complete
2016-10-14 09:12:03 : stdout : 88e8571d2ee0: Pull complete
2016-10-14 09:12:03 : stdout : 8b3a1f752216: Pull complete
2016-10-14 09:12:03 : stdout : 8aa917ed1723: Pull complete
2016-10-14 09:12:03 : stdout : e46b954033e9: Pull complete
2016-10-14 09:12:03 : stdout : 27890353805b: Pull complete
2016-10-14 09:12:03 : stdout : 6fd49fdeef2b: Pull complete
2016-10-14 09:12:03 : stdout : 6f56885abba8: Pull complete
2016-10-14 09:12:03 : stdout : 38576cfda9cf: Pull complete
2016-10-14 09:12:03 : stdout : 5e1e523d61e8: Pull complete
2016-10-14 09:12:03 : stdout : Digest: sha256:3b77b911b8d7482ccd398faa37d16a48f06998d3c7cac012561972cf65ae5308
2016-10-14 09:12:03 : stdout : Status: Downloaded newer image for clouder/clouder-salt-master-data:latest
2016-10-14 09:12:03 : stdout :  ---> 5e1e523d61e8
2016-10-14 09:12:03 : stdout : Step 2 : MAINTAINER kenneth@vkdata.dk
2016-10-14 09:12:03 : stdout :  ---> Running in 6fd85a2c7fc0
2016-10-14 09:12:03 : stdout :  ---> 95081ba8ee9a
2016-10-14 09:12:03 : stdout : Removing intermediate container 6fd85a2c7fc0
2016-10-14 09:12:03 : stdout : Step 3 : VOLUME /srv/salt /srv/pillar
2016-10-14 09:12:04 : stdout :  ---> Running in 6eccc92693c4
2016-10-14 09:12:04 : stdout :  ---> b4f1a24c373d
2016-10-14 09:12:04 : stdout : Removing intermediate container 6eccc92693c4
2016-10-14 09:12:04 : stdout : Successfully built b4f1a24c373d
2016-10-14 09:12:04 : host : container-host.clouder-local
2016-10-14 09:12:04 : command : rm -rf /tmp/docker-salt-master-data-20161014.091130
2016-10-14 09:12:04 : host : container-host.clouder-local
2016-10-14 09:12:04 : command : docker run -d -t --restart=always --name docker-salt-master-data docker-salt-master-data-20161014.091130 
2016-10-14 09:12:04 : stdout : 85023b0c4297762a58eea49702765e7279bf82484db72f714accb752bef24068
2016-10-14 09:12:07 : host : container-host.clouder-local
2016-10-14 09:12:07 : command : docker stop docker-salt-master-data
2016-10-14 09:12:07 : stdout : docker-salt-master-data
2016-10-14 09:12:07 : host : container-host.clouder-local
2016-10-14 09:12:07 : command : docker start docker-salt-master-data
2016-10-14 09:12:08 : stdout : docker-salt-master-data
2016-10-14 09:12:11 : ===================
2016-10-14 09:12:11 : FAIL! Reverting...
2016-10-14 09:12:11 : ===================
2016-10-14 09:12:11 : host : container-host.clouder-local
2016-10-14 09:12:11 : command : docker exec docker-salt-master bash -c  "sed -i \"/  'container-host.clouder-local\'/,/END\scontainer-host.clouder-local/d\" /srv/pillar/top.sls "
2016-10-14 09:12:11 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:12:11 : host : container-host.clouder-local
2016-10-14 09:12:11 : command : docker exec docker-salt-master bash -c  "rm /etc/salt/pki/master/minions/container-host.clouder-local "
2016-10-14 09:12:11 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:12:11 : host : container-host.clouder-local
2016-10-14 09:12:11 : command : docker exec docker-salt-master bash -c  "rm /etc/salt/pki/master/minions_denied/container-host.clouder-local "
2016-10-14 09:12:11 : stderr : Error response from daemon: no such id: docker-salt-master
2016-10-14 09:12:11 : ===================
2016-10-14 09:12:11 : FAIL!
2016-10-14 09:12:11 : ===================
```

I have verified that the docker service is running in my container host.

Is there anywhere I can find updated documentation that matches the actual version of the code installed?

**Comment by YannickB** [comment]
Hello,

Yes the documentation is vastly outdated, we are trying to find the time to update it.

To me it looks like you did it the right way, the first container (salt-master-data) was correctly created
```
2016-10-14 09:12:04 : command : docker run -d -t --restart=always --name docker-salt-master-data docker-salt-master-data-20161014.091130 
2016-10-14 09:12:04 : stdout : 85023b0c4297762a58eea49702765e7279bf82484db72f714accb752bef24068
```

But then an error appear, and strangely we don't know which one. Are you sure you have nothing else in the traceback ? Which range did you used ? Maybe a screenshot of the server form screen will help.

**Comment by kenneth-vkd** [comment]
Hi
First thing, I can see that I made a small mistake as I set start port and end port to the same value. When set to different values the server seems to deploy fine in Odoo 9 Community version and I can create the backup-upload container, the backup container, postfix container, bind container, shinken container, proxy container and postgresql container. The odoo container does however not create.
I did manually add a link to Shinken and Postfix, but left the already generated Postgresql link there.
When I created the container it was processing for some time and then it gave this error traceback:

```


Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 888, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/clouder_runner_docker/template.py", line 98, in create
    return super(ClouderContainer, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/container.py", line 1371, in create
    child.create_child_exec()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/container.py", line 1978, in create_child_exec
    'server_id': self.server_id.id or container.server_id.id
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/clouder_runner_docker/template.py", line 98, in create
    return super(ClouderContainer, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/container.py", line 1362, in create
    res = super(ClouderContainer, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 415, in create
    res.do('create', 'deploy_frame')
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 310, in do
    getattr(self, 'do_exec')(action, job_id)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 332, in do_exec
    getattr(self, action)()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 347, in deploy_frame
    self.deploy_links()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 380, in deploy_links
    link.deploy_()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/container.py", line 1905, in deploy_
    'deploy_exec', where=self.container_id)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 310, in do
    getattr(self, 'do_exec')(action, job_id)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/model.py", line 332, in do_exec
    getattr(self, action)()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder/container.py", line 1912, in deploy_exec
    self.control() and self.deploy_link()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder_template_gitlab/template.py", line 177, in deploy_link
    super(ClouderContainerLink, self).deploy_link()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder_template_postgres/template.py", line 71, in deploy_link
    super(ClouderContainerLink, self).deploy_link()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder_template_mysql/template.py", line 113, in deploy_link
    super(ClouderContainerLink, self).deploy_link()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/addons/custom/clouder_template_shinken/template.py", line 196, in deploy_link
    self.container_id.backup_ids[0].ports['nrpe']['hostport'] +
KeyError: 'nrpe'

```
Clicking OK to the message it intially seems that any attempted creation was rolled back, but when trying to click save,it tells that the container does already exist.
Going back to the container list view and clicking the container and then opening the log-file I get this output:
```
2016-10-15 10:57:09 : host : container-host.clouder.vkdata.io
2016-10-15 10:57:09 : command : docker exec testing-salt-master-exec bash -c  "salt container-host.clouder.vkdata.io state.apply container_stop pillar=\"{'container_name': 'testing-odoo-demo-1'}\" "
2016-10-15 10:57:09 : stderr : Error response from daemon: no such id: testing-salt-master-exec
2016-10-15 10:57:09 : host : container-host.clouder.vkdata.io
2016-10-15 10:57:09 : command : docker exec testing-salt-master-exec bash -c  "sed -i \"/containers\/testing-odoo-demo-1/d\" /srv/pillar/top.sls "
2016-10-15 10:57:09 : stderr : Error response from daemon: no such id: testing-salt-master-exec
2016-10-15 10:57:09 : host : container-host.clouder.vkdata.io
2016-10-15 10:57:09 : command : docker exec testing-salt-master-exec bash -c  "rm -rf /srv/salt/containers/build_testing-odoo-demo-1 "
2016-10-15 10:57:09 : stderr : Error response from daemon: no such id: testing-salt-master-exec
2016-10-15 10:57:09 : host : container-host.clouder.vkdata.io
2016-10-15 10:57:09 : command : docker exec testing-salt-master-exec bash -c  "rm -rf /srv/pillar/containers/testing-odoo-demo-1.sls "
2016-10-15 10:57:09 : stderr : Error response from daemon: no such id: testing-salt-master-exec
2016-10-15 10:57:09 : host : container-host.clouder.vkdata.io
2016-10-15 10:57:09 : command : docker exec testing-salt-master-exec bash -c  "salt container-host.clouder.vkdata.io state.apply container_purge pillar=\"{'container_name': 'testing-odoo-demo-1'}\" "
2016-10-15 10:57:09 : stderr : Error response from daemon: no such id: testing-salt-master-exec
```
The status of the create action is set to done
