### ISSUE TITLE
[BUG][master] No matching record found for external id 'connector.model_queue_job'

### ISSUE THREAD

**Issue by lasley** [clouder-community/clouder#147]
This is primarily a note to self, but anyone is welcome to fix 😉 

Pretty sure this just needs to be moved back into the async module?

To replicate, install `clouder` on a fresh database.

Branch `master`

```
2016-10-24 16:20:23,547 1040 ERROR clouder openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/www/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/var/www/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/var/www/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/www/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/www/odoo/openerp/tools/convert.py", line 845, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/var/www/odoo/openerp/tools/convert.py", line 913, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading clouder failed: file clouder/security/ir.model.access.csv could not be processed:
 Line 1 : No matching record found for external id 'connector.model_queue_job' in field 'Object'
2016-10-24 16:20:23,548 1040 ERROR clouder openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/var/www/odoo/openerp/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/var/www/odoo/openerp/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/var/www/odoo/openerp/http.py", line 320, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/var/www/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/var/www/odoo/openerp/http.py", line 313, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/www/odoo/openerp/http.py", line 963, in __call__
    return self.method(*args, **kw)
  File "/var/www/odoo/openerp/http.py", line 513, in response_wrap
    response = f(*args, **kw)
  File "/var/www/odoo/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/var/www/odoo/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/var/www/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/www/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/var/www/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/www/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/var/www/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/www/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/var/www/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/var/www/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/var/www/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/var/www/odoo/openerp/tools/convert.py", line 845, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/var/www/odoo/openerp/tools/convert.py", line 913, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading clouder failed: file clouder/security/ir.model.access.csv could not be processed:
 Line 1 : No matching record found for external id 'connector.model_queue_job' in field 'Object'
```

**Comment by lasley** [comment]
Closing to track in #150
