### ISSUE TITLE
create the Base

### ISSUE THREAD

**Issue by Hamza-Talibi** [clouder-community/clouder#223]
Hello @YannickB ,
I want to deploy Odoo 10 in the server. So firstly I deploy the node using oneclick (code = odoo10-all) which deploy only 4 service: The backup service,The DNS service,The mail service,The proxy service.
Then I create manually a new service:(Odoo 10 + Postgres).
Finally I get problem in the base: 
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: title - title] 

However the field title isn't declared in xml.
Why oneclick for odoo10-all doesn't create all services like services deployed by the oneclick? Now how can I create the base?

**Comment by lasley** [comment]
Which branch are you using? Master?

**Comment by Hamza-Talibi** [comment]
Yes.
In the node I create Oneclick Deployment, I create a new value to deploy odoo10+postgres :
![odoo10](https://cloud.githubusercontent.com/assets/25642031/24732139/cf91306e-1a66-11e7-8bcd-b47410d2227f.png).
It's only deploy backup, bind, postfix and proxy.
And then I create a service odoo10-all, then I get a problem the container odoo10-exec get stuck in restarting, their log shows: /bin/sh /opt/odoo/files/odoo/odoo.py not found I think the problem in the image odoo10-exec.

**Comment by Hamza-Talibi** [comment]
For the base I have thought to add a field title in xml because is required, However I get error in creating database:
FAIL! Reverting...
2017-04-06 00:37:05,020 3667 INFO db_openexpertiz_odoo10 odoo.addons.clouder.models.model:   File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 362, in deploy_frame
    self.deploy()

  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/base.py", line 819, in deploy
    self.deploy_build()

  File "/home/odoo10/odoo-dev/odoo/addons/clouder_template_odoo/template.py", line 156, in deploy_build
    password=self.admin_password)

  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 439, in __init__
    self.server_version = ver = get_proxy('db').server_version()

  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 402, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose

  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)

  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)

  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)

  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()

  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)

  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
_____________________________________________________________________
 ===================
2017-04-06 00:37:31,977 3667 INFO db_openexpertiz_odoo10 odoo.addons.clouder.models.model: FAIL!
2017-04-06 00:37:31,989 3667 INFO db_openexpertiz_odoo10 odoo.addons.clouder.models.model:   File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 349, in do_exec
    getattr(self, action)()

  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 362, in deploy_frame
    self.deploy()

  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/base.py", line 819, in deploy
    self.deploy_build()

  File "/home/odoo10/odoo-dev/odoo/addons/clouder_template_odoo/template.py", line 156, in deploy_build
    password=self.admin_password)

  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 439, in __init__
    self.server_version = ver = get_proxy('db').server_version()

  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 402, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose

  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)

  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)

  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)

  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()

  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)

  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
____________________________________________________________
Traceback (most recent call last):
  File "/home/odoo10/odoo-dev/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo10/odoo-dev/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo10/odoo-dev/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo10/odoo-dev/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo10/odoo-dev/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo10/odoo-dev/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo10/odoo-dev/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo10/odoo-dev/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo10/odoo-dev/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo10/odoo-dev/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo10/odoo-dev/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/base.py", line 599, in create
    return super(ClouderBase, self).create(vals)
  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 434, in create
    res.do('create', 'deploy_frame')
  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 335, in do
    getattr(self, 'do_exec')(action, job_id)
  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 349, in do_exec
    getattr(self, action)()
  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/model.py", line 362, in deploy_frame
    self.deploy()
  File "/home/odoo10/odoo-dev/odoo/addons/clouder/models/base.py", line 819, in deploy
    self.deploy_build()
  File "/home/odoo10/odoo-dev/odoo/addons/clouder_template_odoo/template.py", line 156, in deploy_build
    password=self.admin_password)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 439, in __init__
    self.server_version = ver = get_proxy('db').server_version()
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 402, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connexion refusée

**Comment by Hamza-Talibi** [comment]
What Sould I do now?

**Comment by lasley** [comment]
That deploy oneclick looks a lot different than the way I do it. Are you initiating it from the node form?

**Comment by Hamza-Talibi** [comment]
Yes.
How do you deploy an application (odoo 10 for example) using the node form?

**Comment by Hamza-Talibi** [comment]
@YannickB  How can I deploy odoo10 in a distance server using the Oneclick Deployment?
As you see above, I tried, but the oneclick only deploy (backup, bind, postfix and proxy), then I created service odoo10 manually in which I had bug: the container got stuck in restarting and their log shows: /bin/sh /opt/odoo/files/odoo/odoo.py not found.
After, in the base the field title is required, but isn't declared in the view.xml, I added it to overcome the error.
Finally I get error: connection refused when configuring the database ( you can see the traceback above).
Thank you

**Comment by YannickB** [comment]
Hi @Hamza-Talibi , I'm not sure but maybe you need to wait that #220 is merged, I made a lot of update here which may cause the error you're describing.

@lasley Do you think I can merge it now ?
