### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)

### ISSUE THREAD

**Issue by ErrafayM** [clouder-community/clouder#23]
Hi , when i try to save my registry container i get this error : 

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 937, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/clouder/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/clouder/clouder/clouder_template_registry/clouder_template_registry.py", line 70, in deploy
    return super(ClouderContainer, self).deploy()
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/clouder/clouder/clouder_container.py", line 703, in deploy
    self.deploy_post()
  File "/home/odoo/odoo-dev/odoo/clouder/clouder/clouder_template_registry/clouder_template_registry.py", line 78, in deploy_post
    ssh = self.connect(self.fullname)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/clouder/clouder/clouder_model.py", line 412, in connect
    "Error : " + str(inst)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)

**Comment by YannickB** [comment]
Hello,

Do you have any place where you used an accent? For example the name of the container?

**Comment by ErrafayM** [comment]
Thanks for responding , no any of my containers got an accents , can it be because of my debian is in french ? should i try changing it to english ?

**Comment by YannickB** [comment]
Please check https://github.com/clouder-community/clouder/blob/8.0/clouder/clouder_model.py line 412, i seems you are raising an error anyway, you shall try to check you ssh connection.
 It seems it's the error message itself which contains an accent, and yes maybe it's because your debian is in french but you shall be able to resolve the ssh problem without changing the system language.

If you can't make it work, I can provide a Clouder instance on my server so you can move forward

**Comment by ErrafayM** [comment]
It was indeed an SSH problem also , still have to figure it out , but i got rid of the error by  changing my system to english , thank you sir .

**Comment by ErrafayM** [comment]
I fixed my problem it wasnt even the SSH but my server Docker wasnt really running . thanks again for your help and keep doing the great job !
