### ISSUE TITLE
Error - Adding base problem

### ISSUE THREAD

**Issue by ErrafayM** [clouder-community/clouder#26]
Hi since yesterday i'm having an issue adding a base , i suspect postgres is the problem (img_postgres with a postgresql9.4 and 9.1 path) , but have no clue how to resolve it 

Error : could not translate host name "postgres" to address: Name or service not known

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 937, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/clouder-8.0/clouder/clouder_base.py", line 378, in create
    return super(ClouderBase, self).create(vals)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/clouder-8.0/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/clouder-8.0/clouder/clouder_base.py", line 595, in deploy
    res = self.deploy_create_database()
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/addons/clouder-8.0/clouder_template_odoo/clouder_template_odoo.py", line 217, in deploy_create_database
    user_password=self.admin_password)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 639, in create_database
    user_password)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 383, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault could not translate host name "postgres" to address: Name or service not known
: 'Traceback (most recent call last):\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/service/db.py", line 73, in dispatch\n    return fn(*params)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/service/db.py", line 90, in exp_create_database\n    _create_empty_database(db_name)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/service/db.py", line 77, in _create_empty_database\n    with closing(db.cursor()) as cr:\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/sql_db.py", line 575, in cursor\n    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/sql_db.py", line 181, in __init__\n    self._cnx = pool.borrow(dsn)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/sql_db.py", line 464, in _locked\n    return fun(self, *args, **kwargs)\n  File "/opt/versions/odoo-clouder/8.0.20150616.162105/parts/odoo/openerp/sql_db.py", line 526, in borrow\n    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)\n  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, async=async)\nOperationalError: could not translate host name "postgres" to address: Name or service not known\n\n'>

**Comment by YannickB** [comment]
Hello,

Are postgres and Odoo on the same server? Until now, all my installations are on the same server and the communication are done by docker link. 
On the log of the odoo container creation, car you check the docker run command to verify the name of the docker link ? Copy / paste the docker run command here if needed.

**Comment by houssine78** [comment]
it's maybe related to the other issue reported https://github.com/clouder-community/clouder/issues/25

**Comment by ErrafayM** [comment]
Yes they are on the same server . here is the docker run 

sudo docker run -d -p 14018:22 -p 14019:8069 -p 14020:7069 -p 14021:6069 -p 14022:5069 -p 14023:4069 -v /opt/services:/opt/versions:ro --link www-postgres:postgres --link www-postfix:postfix -v /opt/keys/www-clouder_192.168.1.6:/opt/keys --name www-clouder localhost:14000/img_odoo:8.0.20150616.150922

**Comment by YannickB** [comment]
Ok so from what I see 'postgres' shall be the good hostname when we are inside the odoo container. Can you try a ping postgres from the odoo container, or try to connect with the psql binary and the odoo credentials in /opt/odoo/production/etc/config.

**Comment by ErrafayM** [comment]
Fixed it . not sure what it was but what i did is i did a reinstall to the odoo container and somehow it did add two lines on the /etc/hosts 

172.17.0.1      postgres 56fb9bec0d5d www-postgres
172.17.0.7      postfix e8ccee80b69e www-postfix

Wasnt the only problem because i had to manualy change pg_hba in the postgres container 

host all all 0.0.0.0/0 md5 

after this i could create a base .

**Comment by YannickB** [comment]
Ok good.

Regarding the pg_hba, this is due to the version change #25, shall be ok now with the last version of the code.
