### ISSUE TITLE
Error occurred while creating registry container

### ISSUE THREAD

**Issue by collex100** [clouder-community/clouder#43]
**I connected the server. I want to create a registry container, but get this error:**

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_template_registry/clouder_template_registry.py", line 70, in deploy
    return super(ClouderContainer, self).deploy()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_container.py", line 629, in deploy
    self.purge()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_container.py", line 719, in purge
    self.purge_key()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_container.py", line 786, in purge_key
    self.fullname, self.home_directory + '/.ssh/config'])
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_model.py", line 484, in execute_local
    stderr=subprocess.STDOUT, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**The file odoo-server.log there is a record:**

2015-08-04 15:28:32,412 13549 INFO pandaplus openerp.addons.clouder.clouder_model: command : /opt/odoo/odoo/addons/clouder/res/sed.sh www-panda1-registry_myservername /opt/odoo/.ssh/config
2015-08-04 15:28:32,427 13549 INFO pandaplus openerp.addons.clouder.clouder_model: ===================
2015-08-04 15:28:32,436 13549 INFO pandaplus openerp.addons.clouder.clouder_model: FAIL! Reverting...
2015-08-04 15:28:32,439 13549 INFO pandaplus openerp.addons.clouder.clouder_model: ===================
2015-08-04 15:28:32,455 13549 INFO pandaplus openerp.addons.clouder.clouder_model: This base container not be saved or the backup isnt configured in conf, skipping save container
2015-08-04 15:28:32,462 13549 INFO pandaplus openerp.addons.clouder.clouder_model: command : /opt/odoo/odoo/addons/clouder/res/sed.sh www-panda1-registry_myservername /opt/odoo/.ssh/config

**I do not understand what is wrong in the file /opt/odoo/.ssh/config ?**

**Comment by ErrafayM** [comment]
I have just created a registry container without any problem . check the postgresql log . probably you didnt add your odoo user as a role .

**Comment by collex100** [comment]
I pulled on github modules directly on the server everything started working. Before I used FTP and was a mistake. Although using user rights odoo application. Something was wrong with the rights to modules Clouder. Registry container now created. Thanks!
