### ISSUE TITLE
Error when build the application

### ISSUE THREAD

**Issue by collex100** [clouder-community/clouder#44]
**When I build the applicationI Odoo, I indicate the archive container and click on the build button, but I got this error(odoo-server.log):**

2015-08-05 16:52:10,844 13549 INFO pandaplus openerp.addons.clouder.clouder_model: connect: ssh www-panda1-archive_panda1.pandaplus.biz
2015-08-05 16:52:10,858 13549 INFO pandaplus openerp.addons.clouder.clouder_model: ===================
2015-08-05 16:52:10,860 13549 INFO pandaplus openerp.addons.clouder.clouder_model: FAIL! Reverting...
2015-08-05 16:52:10,861 13549 INFO pandaplus openerp.addons.clouder.clouder_model: ===================
2015-08-05 16:52:10,867 13549 INFO pandaplus openerp.addons.clouder.clouder_model: connect: ssh www-panda1-archive_panda1.pandaplus.biz
2015-08-05 16:52:10,892 13549 ERROR pandaplus openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_application.py", line 291, in build
    'archive_id': self.archive_id and self.archive_id.id})
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_application.py", line 414, in deploy
    ssh = self.connect(self.archive_id.fullname)
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_model.py", line 412, in connect
    "Error : " + str(inst)))

**This log archive containe:**

command : /opt/odoo/odoo/addons/clouder/res/sed.sh www-panda1-archive_panda1.pandaplus.biz /opt/odoo/.ssh/config
command : rm -rf /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz
command : rm -rf /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz.pub
connect: ssh panda1.pandaplus.biz
command : rm -rf /opt/keys/www-panda1-archive_panda1.pandaplus.biz/authorized_keys
stdout : 
stderr : 
connect: ssh panda1.pandaplus.biz
connect: ssh panda1.pandaplus.biz
command : docker stop www-panda1-archive
stdout : 
stderr : Error response from daemon: no such id: www-panda1-archive
Error: failed to stop containers: [www-panda1-archive]

command : sudo docker rm www-panda1-archive
stdout : 
stderr : Error response from daemon: no such id: www-panda1-archive
Error: failed to remove containers: [www-panda1-archive]

command : rm -rf /opt/keys/www-panda1-archive_panda1.pandaplus.biz
stdout : 
stderr : 
connect: ssh panda1.pandaplus.biz
command : netstat -an | grep 14003
stdout : 
stderr : 
command : /opt/odoo/odoo/addons/clouder/res/sed.sh www-panda1-archive_panda1.pandaplus.biz /opt/odoo/.ssh/config
command : rm -rf /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz
command : rm -rf /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz.pub
connect: ssh panda1.pandaplus.biz
command : rm -rf /opt/keys/www-panda1-archive_panda1.pandaplus.biz/authorized_keys
stdout : 
stderr : 
command : ssh-keygen -t rsa -C mymail@gmail.com -f /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz -N 
stdout : Generating public/private rsa key pair.

stdout : Your identification has been saved in /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz.

stdout : Your public key has been saved in /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz.pub.

stdout : The key fingerprint is:

stdout : 94:a8:f3:6c:91:91:d7:3c:db:72:84:5b:e4:71:52:78 mymail@gmail.com

stdout : The key's randomart image is:

stdout : +--[ RSA 2048]----+

stdout : |            +oo  |

stdout : |       o + +.+E  |

stdout : |      + + = +.   |

stdout : |     . =   B     |

stdout : |    o o S + o    |

stdout : |     + .   o     |

stdout : |      +          |

stdout : |     .           |

stdout : |                 |

stdout : +-----------------+

connect: ssh panda1.pandaplus.biz
command : mkdir -p /opt/keys/www-panda1-archive_panda1.pandaplus.biz
stdout : 
stderr : 
send : /opt/odoo/.ssh/keys/www-panda1-archive_panda1.pandaplus.biz.pub to /opt/keys/www-panda1-archive_panda1.pandaplus.biz/authorized_keys
command : sudo docker run -d --restart=always -p 14003:22 -v /opt/keys/www-panda1-archive_panda1.pandaplus.biz:/opt/keys --name www-panda1-archive localhost:14000/img_archive:1.20150805.144447
stdout : 
stderr : Unable to find image 'localhost:14000/img_archive:1.20150805.144447' locally
Pulling repository localhost:14000/img_archive
Error: image img_archive:1.20150805.144447 not found

connect: ssh panda1.pandaplus.biz
command : docker stop www-panda1-archive
stdout : 
stderr : Error response from daemon: no such id: www-panda1-archive
Error: failed to stop containers: [www-panda1-archive]

connect: ssh panda1.pandaplus.biz
command : docker start www-panda1-archive
stdout : 
stderr : Error response from daemon: no such id: www-panda1-archive
Error: failed to start containers: [www-panda1-archive]

This base container not be saved or the backup isnt configured in conf, skipping save container

**Comment by ErrafayM** [comment]
check if your archive container is started , if it is check your www-panda1-archive logs in clouder .

**Comment by ErrafayM** [comment]
check your img_archive log also , rebuilt it if it's needed also reinstall your www-panda1-archive .

**Comment by collex100** [comment]
I did rebuilt img_archive, and then did reinstall  www-panda1-archive. The application odoo was build. Thanks!
