### ISSUE TITLE
Stuck on building odoo application

### ISSUE THREAD

**Issue by AyoubZahid** [clouder-community/clouder#56]
Hello guys,

When i try to build the odoo application a get this  error:
>Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/clouder/clouder/clouder_application.py", line 291, in build
    'archive_id': self.archive_id and self.archive_id.id})
  File "/opt/odoo/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/clouder/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/clouder/clouder/clouder_application.py", line 418, in deploy
    self.build_application()
  File "/opt/odoo/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/clouder/clouder_template_odoo/clouder_template_odoo.py", line 94, in build_application
    self.full_archivepath + '/parts/http.patch')
  File "/opt/odoo/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/clouder/clouder/clouder_model.py", line 466, in send
    sftp.put(source, destination)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 669, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 621, in putfo
    with self.file(remotepath, 'wb') as fr:
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 729, in _request
    return self._read_response(num)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 776, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 802, in _convert_status
    raise IOError(errno.ENOENT, text)
IOError: [Errno 2] No such file

On the log of odoo server i get this

>  /opt/archives/odoo-odoo/8.0.20151023.154044/sandbox/lib/python2.7/site-packages/pip/wheel.py
  /opt/archives/odoo-odoo/8.0.20151023.154044/sandbox/lib/python2.7/site-packages/pip/wheel.pyc
Proceed (y/n)?   Successfully uninstalled pip

>2015-10-23 15:40:48,260 3377 INFO saas openerp.addons.clouder.clouder_model: stderr :
2015-10-23 15:40:48,263 3377 INFO saas openerp.addons.clouder.clouder_model: command : sandbox/bin/python bootstrap.py
2015-10-23 15:40:48,266 3377 INFO saas openerp.addons.clouder.clouder_model: path : /opt/archives/odoo-odoo/8.0.20151023.154044
2015-10-23 15:40:50,680 3377 INFO saas openerp.addons.clouder.clouder_model: stdout :
2015-10-23 15:40:50,685 3377 INFO saas openerp.addons.clouder.clouder_model: stderr : Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.4.zip
Extracting in /tmp/tmprPMQ9D
Now working in /tmp/tmprPMQ9D/setuptools-18.4
Building a Setuptools egg in /tmp/bootstrap-WsclVx
/tmp/bootstrap-WsclVx/setuptools-18.4-py2.7.egg
While:
  Initializing.

>An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1991, in main
    user_defaults, command, args)
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 231, in __init__
    data['buildout'].copy(), override, set()))
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1605, in _open
    fp, filename_for_logging, _default_globals)
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/configparser.py", line 207, in parse
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /opt/archives/odoo-odoo/8.0.20151023.154044/buildout.cfg, line: 2
'git clone http://github.com/odoo/odoo.git parts/odoo -b 8.0\n'

>2015-10-23 15:40:50,688 3377 INFO saas openerp.addons.clouder.clouder_model: command : bin/buildout
2015-10-23 15:40:50,691 3377 INFO saas openerp.addons.clouder.clouder_model: path : /opt/archives/odoo-odoo/8.0.20151023.154044
2015-10-23 15:40:50,738 3377 INFO saas openerp.addons.clouder.clouder_model: stdout :
2015-10-23 15:40:50,741 3377 INFO saas openerp.addons.clouder.clouder_model: stderr : bash: bin/buildout: No such file or directory

>2015-10-23 15:40:50,744 3377 INFO saas openerp.addons.clouder.clouder_model: command : sed -i "s/\/opt\/archives/\/opt\/versions/g" /opt/archives/odoo-odoo/8.0.20151023.154044/bin/start_odoo
2015-10-23 15:40:50,798 3377 INFO saas openerp.addons.clouder.clouder_model: stdout :
2015-10-23 15:40:50,802 3377 INFO saas openerp.addons.clouder.clouder_model: stderr : sed: can't read /opt/archives/odoo-odoo/8.0.20151023.154044/bin/start_odoo: No such file or directory

>2015-10-23 15:40:50,805 3377 INFO saas openerp.addons.clouder.clouder_model: command : sed -i "s/\/opt\/archives/\/opt\/versions/g" /opt/archives/odoo-odoo/8.0.20151023.154044/bin/buildout
2015-10-23 15:40:50,901 3377 INFO saas openerp.addons.clouder.clouder_model: stdout :
2015-10-23 15:40:50,906 3377 INFO saas openerp.addons.clouder.clouder_model: stderr : sed: can't read /opt/archives/odoo-odoo/8.0.20151023.154044/bin/buildout: No such file or directory

>2015-10-23 15:40:50,992 3377 INFO saas paramiko.transport.sftp: [chan 8] Opened sftp connection (server version 3)
2015-10-23 15:40:50,993 3377 INFO saas openerp.addons.clouder.clouder_model: send : /opt/clouder/clouder_template_odoo/res/http.patch to /opt/archives/odoo-odoo/8.0.20151023.154044/parts/http.patch
2015-10-23 15:40:50,997 3377 INFO saas openerp.addons.clouder.clouder_model: ===================
2015-10-23 15:40:51,000 3377 INFO saas openerp.addons.clouder.clouder_model: FAIL! Reverting...
2015-10-23 15:40:51,003 3377 INFO saas openerp.addons.clouder.clouder_model: ===================
2015-10-23 15:40:51,014 3377 INFO saas openerp.addons.clouder.clouder_model: connect: ssh www-archive_agilorg.ma
2015-10-23 15:40:51,034 3377 INFO ? paramiko.transport: Connected (version 2.0, client OpenSSH_6.7p1)

**Comment by AyoubZahid** [comment]
I think there is something here : 

>2015-10-23 15:40:50,685 3377 INFO saas openerp.addons.clouder.clouder_model: stderr : Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.4.zip
Extracting in /tmp/tmprPMQ9D
Now working in /tmp/tmprPMQ9D/setuptools-18.4
Building a Setuptools egg in /tmp/bootstrap-WsclVx
/tmp/bootstrap-WsclVx/setuptools-18.4-py2.7.egg
While:
  Initializing.

>An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1991, in main
    user_defaults, command, args)
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 231, in __init__
    data['buildout'].copy(), override, set()))
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/buildout.py", line 1605, in _open
    fp, filename_for_logging, _default_globals)
  File "/tmp/bootstrap-WsclVx/zc.buildout-2.4.5-py2.7.egg/zc/buildout/configparser.py", line 207, in parse
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /opt/archives/odoo-odoo/8.0.20151023.154044/buildout.cfg, line: 2
'git clone http://github.com/odoo/odoo.git parts/odoo -b 8.0\n'

**Comment by YannickB** [comment]
Ok, this is not normal that the buildout code is used while there is a start with a git clone, I guess there is something wrong with my last commit. I'll try to correct it asap, thank for the feedback

**Comment by AyoubZahid** [comment]
Hello Yannick,

In the buildfile of odoo application there is an empty line before 'git', that's why it return false.

i removed the empty line at the beginning and it worked.

**Comment by YannickB** [comment]
Just when I was starting to work on it, ok thanks for the info I'll correct it
