### ISSUE TITLE
Error when adding the Base (last step in documentation)

### ISSUE THREAD

**Issue by ChristopherPa** [clouder-community/clouder#63]
hi,

i get an error if i try to add the Base.
this is the log

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_base.py", line 378, in create
    return super(ClouderBase, self).create(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_base.py", line 595, in deploy
    res = self.deploy_create_database()
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder_template_odoo/clouder_template_odoo.py", line 218, in deploy_create_database
    ':' + self.service_id.port['hostport'])
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 438, in __init__
    self.server_version = ver = get_proxy('db').server_version()
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 401, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

```
thx for your help.

**Comment by ErrafayM** [comment]
Can you check if your postgresql is started on your postgresql container (www-postgres)?

**Comment by ChristopherPa** [comment]
I checked the status and the postgresql on my postgresql container was down. So i started it manually with the command 

    docker exec www-postgres /etc/init.d/postgresql start

But i still get an error when i try to add the base.

Log of the Error:
```
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_base.py", line 378, in create
    return super(ClouderBase, self).create(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder/clouder_base.py", line 595, in deploy
    res = self.deploy_create_database()
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/clouder_template_odoo/clouder_template_odoo.py", line 218, in deploy_create_database
    ':' + self.service_id.port['hostport'])
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 438, in __init__
    self.server_version = ver = get_proxy('db').server_version()
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 401, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

```

**Comment by ErrafayM** [comment]
Reinstall your service, then install again a new base.

**Comment by ChristopherPa** [comment]
i reinstalled the service but i still get the same error. any other idea what can i do?

thx for your help.

**Comment by ErrafayM** [comment]
Check your Service logs. or check your containers(Bind,Shinken,Postfix,Proxy and Backup) linked to your base logs, probably something is not started or something bad installed.

**Comment by ChristopherPa** [comment]
ok i checked every log of all deployed containers. i think i found the problem. 
In every log it says that the container cant connect via ssh to the host. 
But i have no problem to get a ssh connection to host with terminal. 
The odoo-server is placed at the localhost. Maybe there is a problem, when localhost and client are on the same computer. what do u think? 

typical log of the conatiner deployment:

``` 
stderr: ssh: connect to host localhost port: 14009: connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync: error: error in rsync protocol data stream (code 12) at lo.c(226) [Receiver=3.1.1]
```

In the clouder forum is a thread with a similar problem but there is no solution. 
[link to the forum/thread] (https://www.goclouder.net/forum/help-1/question/how-can-one-configure-the-same-server-where-the-clouder-instance-is-installed-10)

Maybe there is a solution now.

**Comment by ErrafayM** [comment]
Have you copied your ssh key in /root/.ssh/authorized_keys ?

**Comment by ErrafayM** [comment]
Having your client and docker on same server has nothing to do with it, i have tested it many times with no issue. check your iptables or your ssh configuration.

**Comment by ChristopherPa** [comment]
Hey there... we still have the problem, that we cant add the base (last step in documentation/tutorial).
Because of that we build automatic installation of clouder and docker in different VM's. 
Look at https://github.com/ChristopherPa/VLBA.OvGU.de/tree/master/Project%20Clouder 

The requirements and the installation instruction are in the README file. 
Maybe someone can test it to compehend our problem and give us a solution for the issue.

Thx for your help

**Comment by YannickB** [comment]
Closing the ticket
