### ISSUE TITLE
Error when adding the Base

### ISSUE THREAD

**Issue by lvalenzu** [clouder-community/clouder#77]
Hello:

i define the base and when save, this error appear:
------------------------------------
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/server/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/server/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/server/openerp/custom/addons/clouder/clouder_base.py", line 378, in create
    return super(ClouderBase, self).create(vals)
  File "/opt/odoo/server/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server/openerp/custom/addons/clouder/clouder_model.py", line 310, in create
    res.deploy()
  File "/opt/odoo/server/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server/openerp/custom/addons/clouder/clouder_base.py", line 595, in deploy
    res = self.deploy_create_database()
  File "/opt/odoo/server/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/server/openerp/custom/addons/clouder_template_odoo/clouder_template_odoo.py", line 228, in deploy_create_database
    user_password=self.admin_password)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 657, in create_database
    user_password)
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 401, in <lambda>
    wrapper = lambda s, *args: s._dispatch(name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault FATAL:  password authentication failed for user "www_clouder_production"
FATAL:  password authentication failed for user "www_clouder_production"
: 'Traceback (most recent call last):\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/http.py", line 115, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/service/db.py", line 73, in dispatch\n    return fn(*params)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/service/db.py", line 90, in exp_create_database\n    _create_empty_database(db_name)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/service/db.py", line 77, in _create_empty_database\n    with closing(db.cursor()) as cr:\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/sql_db.py", line 575, in cursor\n    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/sql_db.py", line 181, in __init__\n    self._cnx = pool.borrow(dsn)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/sql_db.py", line 464, in _locked\n    return fun(self, *args, **kwargs)\n  File "/opt/versions/odoo-clouder/8.0.20151216.191049/parts/odoo/openerp/sql_db.py", line 526, in borrow\n    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)\n  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, async=async)\nOperationalError: FATAL:  password authentication failed for user "www_clouder_production"\nFATAL:  password authentication failed for user "www_clouder_production"\n\n'>
-------------------------------------------
I check the postgres container, and is online

regards

**Comment by ErrafayM** [comment]
This is a problem due to your Database, even if your postgres container is online it doesnt mean your Postgresql service is also started. in your docker server type in the console 
```
docker exec [your_postgres_container] /etc/init.d/postgresql status
```
If it is online, reinstall your Service and install again your base.

**Comment by YannickB** [comment]
Closing old tickets
